/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNative */

#ifndef _Included_JNative
#define _Included_JNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNative
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNative_Hello
  (JNIEnv *, jobject);

/*
 * Class:     JNative
 * Method:    Sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNative_Sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNative
 * Method:    Stat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNative_Stat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
